In [ ]:
## Numpy 

In [18]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [20]:
import numpy as np

a = np.array((1,2,3,4,5))
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [21]:
import numpy as np

a = np.array({1,2,3,4,5})
print(a)
type(a)

{1, 2, 3, 4, 5}


numpy.ndarray

In [22]:
import numpy as np

a = np.array({'A':1,'B':2})
print(a)
type(a)

{'A': 1, 'B': 2}


numpy.ndarray

In [24]:
## Empty numpy array 

import numpy as np 

arr = np.array([])
arr

array([], dtype=float64)

In [29]:
## ND Array Initialisation : Helper functions ( zeroes, ones )

import numpy as np 

zer = np.zeros((3,6))
print(zer)

onz = np.ones((4,7))
print(onz)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [33]:
## ND Array Initialisation : Helper functions ( zeroes, ones )

import numpy as np 

zer = np.zeros([3,6])
print(zer)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [36]:
## Arange : Start, Stop, Stepsize 

np.arange(10,50,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [41]:
## linspace is equal spaced numbers 

np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [44]:
len(dir(np))

608

In [46]:
np.__version__

'1.21.5'

In [47]:
np.full([3,6],"India")

array([['India', 'India', 'India', 'India', 'India', 'India'],
       ['India', 'India', 'India', 'India', 'India', 'India'],
       ['India', 'India', 'India', 'India', 'India', 'India']],
      dtype='<U5')

In [48]:
np.full((3,6),3.1415)

array([[3.1415, 3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
       [3.1415, 3.1415, 3.1415, 3.1415, 3.1415, 3.1415]])

In [50]:
np.random.random((4,5))

array([[0.58602949, 0.99611937, 0.31130229, 0.05371283, 0.70785298],
       [0.7640993 , 0.48972958, 0.8339357 , 0.0306125 , 0.37931381],
       [0.63088467, 0.31955729, 0.1715205 , 0.86056062, 0.05215872],
       [0.51819753, 0.69406214, 0.99279711, 0.62116468, 0.22947267]])

In [ ]:
#### Array insepction 

In [52]:
arr = np.random.random((4,5))
arr

array([[0.11537075, 0.91648005, 0.51575921, 0.45878976, 0.13338744],
       [0.97786218, 0.41926138, 0.07454849, 0.70636915, 0.63744773],
       [0.08431154, 0.34092482, 0.64516269, 0.7626317 , 0.13663158],
       [0.84510077, 0.17854611, 0.73250129, 0.62157337, 0.3073264 ]])

In [53]:
## row X column
arr.shape

(4, 5)

In [54]:
# Number of elements in the array
arr.size

20

In [67]:
## The dimension of the array ( 1D, 2D, 3D.. )
print(arr.ndim)
print("---------------------------")

r = np.array([2,2,2])
print(r)
print(r.ndim)

print("---------------------------")
rr = np.array([[2,2,2],[3,3,3]])
print(rr)
print(rr.ndim)

print("---------------------------")
rrr = np.array([[[2,2,2],[3,3,3],[4,4,4]]])
print(rrr)
print(rrr.ndim)

2
---------------------------
[2 2 2]
1
---------------------------
[[2 2 2]
 [3 3 3]]
2
---------------------------
[[[2 2 2]
  [3 3 3]
  [4 4 4]]]
3


In [57]:
## The data type of elements in an array
arr.dtype

dtype('float64')

In [73]:
### reshape and resize in numpy 

# reshape doesnot change the original array 
# resize changes the original array 

ls = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ls)

print(ls.reshape(4,3))
print(ls)

print(ls.resize(6,2))
print(ls)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
None
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [78]:
### Array Mathematics 

# single argument operation
np.sum([10,20,10,20])

60

In [86]:
print(np.array([[10,20],[10,20]]))

print(np.sum([[10,20],[10,20]]))

print(np.sum([[10,20],[10,20]],axis = 0))  ## Column wise addition

print(np.sum([[10,20],[10,20]],axis = 1))  ## Row wise addition 

[[10 20]
 [10 20]]
60
[20 40]
[30 30]


In [90]:
np.add([10,20],[10,20])

array([20, 40])

In [94]:
np.subtract([10,20],[10,20])

array([0, 0])

In [93]:
print(np.diff([[10,20],[10,20]],axis = 0))  ## Column wise addition

print(np.diff([[10,20],[10,20]],axis = 1))  ## Row wise addition 

[[0 0]]
[[10]
 [10]]


In [96]:
np.multiply([10,20],[10,20])

array([100, 400])

In [95]:
np.divide([10,20],[10,20])

array([1., 1.])

In [101]:
#### Comparison of the arrays 

## Equal 

a = [1,2,3,4,5]
b = [1,2,3,4,50]

print(np.equal(a,b))

## Array equal 

a = [1,2,3,4,5]
b = [1,2,3,4,50]

print(np.array_equal(a,b))

[ True  True  True  True False]
False


In [144]:
a = np.random.random([3,4])
b = np.random.random([3,4])

print(a)
print(b)

np.equal(a,b)

[[0.58550707 0.67500163 0.09981625 0.53771242]
 [0.09447007 0.14595617 0.71095298 0.79979994]
 [0.82833024 0.72895429 0.60283834 0.6750038 ]]
[[0.614929   0.92222637 0.19099474 0.706019  ]
 [0.28610377 0.48707819 0.21564395 0.00709881]
 [0.99582819 0.04998899 0.29275247 0.7802733 ]]


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [151]:
np.random.seed(1017)
a=np.random.random((3,4))
print(a)

np.random.seed(1017)
b=np.random.random((3,4))
print(b)

np.array_equal(a,b)

[[0.11253549 0.92045486 0.47301466 0.6590571 ]
 [0.78308441 0.51262062 0.69907647 0.39001515]
 [0.80449074 0.62391332 0.62826469 0.13168347]]
[[0.11253549 0.92045486 0.47301466 0.6590571 ]
 [0.78308441 0.51262062 0.69907647 0.39001515]
 [0.80449074 0.62391332 0.62826469 0.13168347]]


True

In [155]:
## Aggregation functions in numpy 

a = np.array([1,2,3,4,5,23,43,12,23,45,234,12234,43,43,43])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

12629
1
12234
1052.4166666666667
17.5
1.0
3371.939018288373


In [ ]:
## Explore mode 

In [158]:
## Calculation of corrlation coefficient 

x = np.random.random((4,4))
print(x)

cc = np.corrcoef(x)
print(cc)

[[0.4585235  0.33801889 0.90240329 0.02984286]
 [0.62227332 0.54211072 0.5455967  0.46551511]
 [0.11455275 0.0113933  0.31268572 0.10220149]
 [0.96229321 0.3348193  0.24029417 0.78776711]]
[[ 1.          0.49763134  0.78287939 -0.55538056]
 [ 0.49763134  1.          0.06116429  0.20216171]
 [ 0.78287939  0.06116429  1.         -0.33648809]
 [-0.55538056  0.20216171 -0.33648809  1.        ]]


In [161]:
## random.random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [178]:
## Slicing

ls = np.array(['S','A','N','F','R','A','N','C','I','S','C','O'])
ls 

print(ls[7:])
print(ls[-5:])
print(ls[7:12])
print(ls[-5:12])


['C' 'I' 'S' 'C' 'O']
['C' 'I' 'S' 'C' 'O']
['C' 'I' 'S' 'C' 'O']
['C' 'I' 'S' 'C' 'O']


In [185]:
ls = np.array(['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P'])

ls.resize(4,4)
ls

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P']], dtype='<U1')

In [188]:
ls[0:1,0:1]

array([['A']], dtype='<U1')

In [190]:
ls[0:1,2:]

array([['C', 'D']], dtype='<U1')

In [191]:
ls[1:3,1:2]

array([['F'],
       ['J']], dtype='<U1')

In [192]:
ls[2:3,2:3]

array([['K']], dtype='<U1')

In [193]:
ls[2:,2:]

array([['K', 'L'],
       ['O', 'P']], dtype='<U1')

In [204]:
## Array manipulation 

# Concatination 

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

np.concatenate((a,b), axis=0)

#np.concatenate((a,b), axis=1)  # Doesnot work 

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [205]:
# Verical stack
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [206]:
# Horizontal stack
np.hstack((a,b))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [209]:
# Column stack 
np.column_stack((a,b))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [230]:
# Hsplit 

ls = np.random.random((6,4))
print(ls)
print('-------------------------')
hsp = np.hsplit(ls,2)
print(hsp)
print('-------------------------')
#print(hsp[0])
#print(hsp[1])

hsp1,hsp2=np.hsplit(ls,2)
hsp1

[[0.50323869 0.84500537 0.26629791 0.98377522]
 [0.16773877 0.17540427 0.39044877 0.20787274]
 [0.28514667 0.94539745 0.25547421 0.17813421]
 [0.65571781 0.57507551 0.62617887 0.42882936]
 [0.58560304 0.43430326 0.41814516 0.33931133]
 [0.52426098 0.58565108 0.55159724 0.50924718]]
-------------------------
[array([[0.50323869, 0.84500537],
       [0.16773877, 0.17540427],
       [0.28514667, 0.94539745],
       [0.65571781, 0.57507551],
       [0.58560304, 0.43430326],
       [0.52426098, 0.58565108]]), array([[0.26629791, 0.98377522],
       [0.39044877, 0.20787274],
       [0.25547421, 0.17813421],
       [0.62617887, 0.42882936],
       [0.41814516, 0.33931133],
       [0.55159724, 0.50924718]])]
-------------------------


array([[0.50323869, 0.84500537],
       [0.16773877, 0.17540427],
       [0.28514667, 0.94539745],
       [0.65571781, 0.57507551],
       [0.58560304, 0.43430326],
       [0.52426098, 0.58565108]])

In [231]:
# Vsplit

ls = np.random.random((6,4))
print(ls)
print('-------------------------')
hsp = np.vsplit(ls,2)
print(hsp)
print('-------------------------')

[[0.78517027 0.29730233 0.52148351 0.93868448]
 [0.79232854 0.77874596 0.79631769 0.95640208]
 [0.92735885 0.18183505 0.9879701  0.39903881]
 [0.67552143 0.64428998 0.38517511 0.40064017]
 [0.38998868 0.13375193 0.60222479 0.22683718]
 [0.64197146 0.20611934 0.0528098  0.90999435]]
-------------------------
[array([[0.78517027, 0.29730233, 0.52148351, 0.93868448],
       [0.79232854, 0.77874596, 0.79631769, 0.95640208],
       [0.92735885, 0.18183505, 0.9879701 , 0.39903881]]), array([[0.67552143, 0.64428998, 0.38517511, 0.40064017],
       [0.38998868, 0.13375193, 0.60222479, 0.22683718],
       [0.64197146, 0.20611934, 0.0528098 , 0.90999435]])]
-------------------------


In [229]:
# Multiple assignment
a,b,c = 1,2,3
print(a)
print(b)
print(c)

1
2
3
